// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'dart_codable_test.dart' as dart_codable_test;

void main() {
  dart_codable_test.main();
}
