name: dart_codable
description: Implementing the Swift Codable Protocol. It provides the abstract classes Encodable, Decodable and Codable to extend a custom class with.
version: 0.0.3
homepage: https://github.com/lunaticcoding/dart_codable

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  reflectable: ^2.2.4

dev_dependencies:
  test_coverage: ^0.4.1
  test: any
